#!/bin/sh
set -e
PATH="/usr/local/bin:$PATH"
dir="`git rev-parse --git-dir`"
trap 'rm -f "$dir/$$.tags"' EXIT
echo "Executing ripper tags"
git ls-files | grep '\.rb$' | \
  ripper-tags --tag-relative -L- -f"$dir/$$.tags"
mv "$dir/$$.tags" "$dir/tags"
